### ISSUE TITLE
An unexpected erroro

### ISSUE THREAD

**Issue by EverydayPancake** [Traphiccone/MM2-Buddy#42]
Hi Traphiccone,

Could I please get assistance with an unexpected error that showed up after downloading your software.  An error message continues to show, and the software is not working.

Thank you for your assistance,
![2023-12-29_15h20_34](https://github.com/Traphiccone/MM2-Buddy/assets/149656926/5c1d631a-2758-47f5-b955-08eea8cdd0bd)

**Comment by Traphiccone** [comment]
Can you send me your log and crashlog file?  They should be in C:\Users\AppData\Roaming\MM2Buddy

**Comment by Traphiccone** [comment]
Can you send me your log and crashlog file?  They should be in
C:\Users\AppData\Roaming\MM2Buddy

**Comment by EverydayPancake** [comment]
Thank you for your assistance.  I am unable to send you the crashlog file, as it doesn't exist.  However, I did create a new folder "MM2Buddy", which now allows the software to work.  I think your software is great!  I can't wait for the new updates.
